{
 "title": "Advanced Traffic Analytics (FastAPI)",
 "refresh": "120s",
 "panels": [
  {
   "title": "Response Distribution (HTTP Statuses)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total) by (status)",
     "legendFormat": "Status {{status}}"
    }
   ]
  },
  {
   "title": "Request Types (HTTP Methods)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total) by (method)",
     "legendFormat": "Method {{method}}"
    }
   ]
  },
  {
   "title": "Multicolored endpoint request flow",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (handler)",
     "legendFormat": "Path: {{handler}}"
    }
   ]
  },
  {
   "title": "Global System Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_highr_seconds_bucket[1m])) by (le))",
     "legendFormat": "Global API p95 Latency"
    }
   ]
  }
 ]
}