services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - "8080:80"
    depends_on:
      - app
      - grafana
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    restart: unless-stopped

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgresql://gen_user:aaa4401&&@636d0d29a15e34ed6dd14940.twc1.net:5432/default_db?sslmode=verify-full"
    restart: unless-stopped

  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/etc/grafana/dashboards/fastapi.json"
      GF_LOG_LEVEL: "warn"
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_USERS_DEFAULT_LANGUAGE: "en-US"
    restart: unless-stopped

